main()
{
   board = 0;

   while (1)
   {
	   print_board(board);
	   asm { @"Your move: " }
	   move = 0;
	   asm{ inn inn }

       asm { @"move is: " }
	   __outn(move);
	   asm { @"\r\n" }

	   exp = exponent(move);
       asm { @"exp is: " }
	   __outn(exp);
	   asm { @"\r\n" }

	   board = board + 1 * exp;

       asm { @"board is: " }
	   __outn(board);
	   asm { @"\r\n" }

	   print_board(board);
	   asm { @"My move!\r\n" }
   }
}

print_board(board)
{
  __outn((board/exponent(0))%3);
  __outn((board/exponent(1))%3);
  __outn((board/exponent(2))%3);
  asm { @"\r\n" }
  __outn((board/exponent(3))%3);
  __outn((board/exponent(4)%3));
  __outn((board/exponent(5))%3);
  asm { @"\r\n" }
  __outn((board/exponent(6))%3);
  __outn((board/exponent(7))%3);
  __outn((board/exponent(8))%3);
  asm { @"\r\n" }
}


exponent(position)
{
  exp = 1;
  for(i=0; i < position; i++)
  {
    exp = exp *3;
  }

  return exp;
}
