main()
{
   board = 0;
   print_board(board);
   asm { @"Your move: " };
}

print_board(board)
{
  __outn((board/1)%3);
  __outn((board/(3))%3);
  __outn((board/(3*3))%3);
  asm { @"\r\n" }
  __outn((board/(3*3*3))%3);
  __outn((board/(3*3*3*3)%3));
  __outn((board/(3*3*3*3*3))%3);
  asm { @"\r\n" }
  __outn((board/(3*3*3*3*3*3))%3);
  __outn((board/(3*3*3*3*3*3*3))%3);
  __outn((board/(3*3*3*3*3*3*3*3))%3);
  asm { @"\r\n" }
}


